/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 lion.gltf --transform
Author: pavlo.menshykh (https://sketchfab.com/pavlo.menshykh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/palace-of-justice-lobby-lion-cac9740eb6064d94bb3262eb33a3fc28
Title: Palace of Justice lobby lion
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/lion-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.delit} position={[-2.35, 0, 1.24]} rotation={[-1.51, 0.06, 0.03]} scale={0.09} />
    </group>
  )
}

useGLTF.preload('/lion-transformed.glb')
